#pragma once

struct OlympiadUserInfo
{
	wstring name;
	INT32 match_count;
	INT32 win_count;
	INT32 olympiad_lose_count;
	INT32 olympiad_point;
};

class COlympiadStatusPages
{
	BOOL m_Enabled;
	CSLock m_Lock;
	UINT m_RefreshTimeout;
	UINT m_RefreshOlyRunning;
	time_t m_RefreshTime;
	vector<OlympiadUserInfo> m_DBOly88;
	vector<OlympiadUserInfo> m_DBOly89;
	vector<OlympiadUserInfo> m_DBOly90;
	vector<OlympiadUserInfo> m_DBOly91;
	vector<OlympiadUserInfo> m_DBOly92;
	vector<OlympiadUserInfo> m_DBOly93;
	vector<OlympiadUserInfo> m_DBOly94;
	vector<OlympiadUserInfo> m_DBOly95;
	vector<OlympiadUserInfo> m_DBOly96;
	vector<OlympiadUserInfo> m_DBOly97;
	vector<OlympiadUserInfo> m_DBOly98;
	vector<OlympiadUserInfo> m_DBOly99;
	vector<OlympiadUserInfo> m_DBOly100;
	vector<OlympiadUserInfo> m_DBOly101;
	vector<OlympiadUserInfo> m_DBOly102;
	vector<OlympiadUserInfo> m_DBOly103;
	vector<OlympiadUserInfo> m_DBOly104;
	vector<OlympiadUserInfo> m_DBOly105;
	vector<OlympiadUserInfo> m_DBOly106;
	vector<OlympiadUserInfo> m_DBOly107;
	vector<OlympiadUserInfo> m_DBOly108;
	vector<OlympiadUserInfo> m_DBOly109;
	vector<OlympiadUserInfo> m_DBOly110;
	vector<OlympiadUserInfo> m_DBOly111;
	vector<OlympiadUserInfo> m_DBOly112;
	vector<OlympiadUserInfo> m_DBOly113;
	vector<OlympiadUserInfo> m_DBOly114;
	vector<OlympiadUserInfo> m_DBOly115;
	vector<OlympiadUserInfo> m_DBOly116;
	vector<OlympiadUserInfo> m_DBOly117;
	vector<OlympiadUserInfo> m_DBOly118;
	vector<wstring> m_PagesOly88;
	vector<wstring> m_PagesOly89;
	vector<wstring> m_PagesOly90;
	vector<wstring> m_PagesOly91;
	vector<wstring> m_PagesOly92;
	vector<wstring> m_PagesOly93;
	vector<wstring> m_PagesOly94;
	vector<wstring> m_PagesOly95;
	vector<wstring> m_PagesOly96;
	vector<wstring> m_PagesOly97;
	vector<wstring> m_PagesOly98;
	vector<wstring> m_PagesOly99;
	vector<wstring> m_PagesOly100;
	vector<wstring> m_PagesOly101;
	vector<wstring> m_PagesOly102;
	vector<wstring> m_PagesOly103;
	vector<wstring> m_PagesOly104;
	vector<wstring> m_PagesOly105;
	vector<wstring> m_PagesOly106;
	vector<wstring> m_PagesOly107;
	vector<wstring> m_PagesOly108;
	vector<wstring> m_PagesOly109;
	vector<wstring> m_PagesOly110;
	vector<wstring> m_PagesOly111;
	vector<wstring> m_PagesOly112;
	vector<wstring> m_PagesOly113;
	vector<wstring> m_PagesOly114;
	vector<wstring> m_PagesOly115;
	vector<wstring> m_PagesOly116;
	vector<wstring> m_PagesOly117;
	vector<wstring> m_PagesOly118;
	vector<wstring> m_PagesItems;
	void LoadINI();
public:
	void Init();
	void TimerExpired();

	BOOL m_LoadCustom;
	//Olympiad Start
	void OnDBLoadOly88(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly89(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly90(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly91(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly92(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly93(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly94(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly95(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly96(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly97(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly98(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly99(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly100(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly101(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly102(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly103(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly104(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly105(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly106(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly107(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly108(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly109(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly110(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly111(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly112(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly113(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly114(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly115(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly116(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly117(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	void OnDBLoadOly118(wstring name, INT32 match_count, INT32 win_count, INT32 olympiad_lose_count, INT32 olympiad_point);
	//Olympiad End

	void RequestStatusOly(User *pUser, UINT nClass);

	void RequestPKStatus(User *pUser, UINT page = 0);
	void RequestPvPStatus(User *pUser, UINT page = 0);
	void RequestEpicItems(User *pUser, UINT page = 0);
	void RequestStatusOly88(User *pUser, UINT page = 0);
	void RequestStatusOly89(User *pUser, UINT page = 0);
	void RequestStatusOly90(User *pUser, UINT page = 0);
	void RequestStatusOly91(User *pUser, UINT page = 0);
	void RequestStatusOly92(User *pUser, UINT page = 0);
	void RequestStatusOly93(User *pUser, UINT page = 0);
	void RequestStatusOly94(User *pUser, UINT page = 0);
	void RequestStatusOly95(User *pUser, UINT page = 0);
	void RequestStatusOly96(User *pUser, UINT page = 0);
	void RequestStatusOly97(User *pUser, UINT page = 0);
	void RequestStatusOly98(User *pUser, UINT page = 0);
	void RequestStatusOly99(User *pUser, UINT page = 0);
	void RequestStatusOly100(User *pUser, UINT page = 0);
	void RequestStatusOly101(User *pUser, UINT page = 0);
	void RequestStatusOly102(User *pUser, UINT page = 0);
	void RequestStatusOly103(User *pUser, UINT page = 0);
	void RequestStatusOly104(User *pUser, UINT page = 0);
	void RequestStatusOly105(User *pUser, UINT page = 0);
	void RequestStatusOly106(User *pUser, UINT page = 0);
	void RequestStatusOly107(User *pUser, UINT page = 0);
	void RequestStatusOly108(User *pUser, UINT page = 0);
	void RequestStatusOly109(User *pUser, UINT page = 0);
	void RequestStatusOly110(User *pUser, UINT page = 0);
	void RequestStatusOly111(User *pUser, UINT page = 0);
	void RequestStatusOly112(User *pUser, UINT page = 0);
	void RequestStatusOly113(User *pUser, UINT page = 0);
	void RequestStatusOly114(User *pUser, UINT page = 0);
	void RequestStatusOly115(User *pUser, UINT page = 0);
	void RequestStatusOly116(User *pUser, UINT page = 0);
	void RequestStatusOly117(User *pUser, UINT page = 0);
	void RequestStatusOly118(User *pUser, UINT page = 0);
	void GeneratePagesPK();
	void GeneratePagesPvP();
	void GeneratePagesOly88();
	void GeneratePagesOly89();
	void GeneratePagesOly90();
	void GeneratePagesOly91();
	void GeneratePagesOly92();
	void GeneratePagesOly93();
	void GeneratePagesOly94();
	void GeneratePagesOly95();
	void GeneratePagesOly96();
	void GeneratePagesOly97();
	void GeneratePagesOly98();
	void GeneratePagesOly99();
	void GeneratePagesOly100();
	void GeneratePagesOly101();
	void GeneratePagesOly102();
	void GeneratePagesOly103();
	void GeneratePagesOly104();
	void GeneratePagesOly105();
	void GeneratePagesOly106();
	void GeneratePagesOly107();
	void GeneratePagesOly108();
	void GeneratePagesOly109();
	void GeneratePagesOly110();
	void GeneratePagesOly111();
	void GeneratePagesOly112();
	void GeneratePagesOly113();
	void GeneratePagesOly114();
	void GeneratePagesOly115();
	void GeneratePagesOly116();
	void GeneratePagesOly117();
	void GeneratePagesOly118();
	void GeneratePagesEpicItems();

};

extern COlympiadStatusPages g_OlympiadStatus;